---
title: "04_embedding"
author: "Crystal"
date: "7/27/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(mosaic)
library("stringr")
library("tidyr")
library("dplyr")
library("readr")
library("tidyverse")
library("DT")
library("RPostgreSQL")
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
setwd("/home/zz3hs/git/dspg21oss/data/dspg21oss/")
embeddings <- read_csv("repo_embedding_3d_pca.csv")

label <- read_csv("github_repos_157k_label.csv")
```

# Clean label
```{r}
colnames(label)


tm_ids =  c("app_blockchain_tm", "app_database_tm", "prog_clang_tm","prog_java_tm", "prog_javascript_tm", "prog_php_tm", "prog_python_tm", "topics_ai_tm", "topics_dataviz_tm")

bert_ids = c("topics_ai_bert", "app_blockchain_bert", "prog_clang_bert","app_database_bert", "topics_dataviz_bert", "prog_java_bert", "prog_javascript_bert", "prog_php_bert", "prog_python_bert")

label_true = label%>%
  filter(bert==T)%>%
  select(-readme)

table(label_true$software_type)


```

# Clean embedding scores
```{r}
#embedding_score <- read_csv("data/dspg21oss/full_repo_sim_scores_co.csv")
```

#Embeddings
```{r}

embeddings_label = left_join(embeddings, label_true, by = "slug")
embeddings_label = embeddings_label%>%
  filter(!is.na(software_type))%>% 
  mutate(category_type = ifelse(test = str_detect(string = software_type, pattern = "^sys_"), yes = "system", no = ""),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "^prog_"), yes = "programming", no = category_type),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "^app_"), yes = "applications", no = category_type),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "^topics_"), yes = "applications", no = category_type),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "database"), yes = "system", no = category_type),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "virtual"), yes = "system", no = category_type))


library(ggforce)
ggplot(embeddings_label, aes(x = x, y = y)) + geom_point()  + aes(colour = category_type) + theme(legend.position = "right") + labs(title = "First two principal components")+
  geom_mark_circle(aes(color = category_type))

ggplot(embeddings_label, aes(x = y, y = z)) + geom_point()  + aes(colour = category_type) + theme(legend.position = "right") + labs(title = "First two principal components")+
  geom_mark_circle(aes(color = category_type))
```


## 3d plot using rgl
```{r}
library(akima)

library(rgl)
x = embeddings_label$x
y = embeddings_label$y
z = embeddings_label$z
s = interp(x,y,z, duplicate =F)

#surface3d(s$x,s$y,s$z)
```

## 3d plot using scatterplot3d
```{r}
library("scatterplot3d") 
table(embeddings_label$software_type)

colors_rgb <- c("#232d4b","#2c4f6b","#0e879c",
            "#60999a","#d1e0bf","#d9e12b",
            "#e6ce3a","#e6a01d","#e57200")
colors <- colors_rgb[as.numeric(embeddings_label$software_type)]


scatterplot3d(x=embeddings_label$x, y=embeddings_label$y, z=embeddings_label$z, color = colors)
```

```{r}
slug_freq_true_bert =label_true%>%
  group_by(slug)%>%
  summarize(N = sum(bert))

ggplot(slug_freq_true_bert, aes(x = N)) + 
  geom_histogram(binwidth = 0.54) + 
  labs(title = "How many software types a repo is classified") 

slug_freq_true_tm =label_true%>%
  group_by(slug)%>%
  summarize(N = sum(term_matching))

ggplot(slug_freq_true_tm, aes(x = N)) + 
  geom_histogram(binwidth = 0.54) + 
  labs(title = "How many software types a repo is classified") 
```

