---
title: "05_results_cutoff2"
author: "Crystal"
date: "7/30/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library("stringr")
library("tidyr")
library("dplyr")
library("readr")
library("tidyverse")
library("DT")
library("RPostgreSQL")
```


1. Used median sentence scores as repo embedding score
2. If median sentence score is greater than mean + 2*sd --> catogorize into that software type
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
setwd("/home/zz3hs/git/dspg21oss/data/dspg21oss/")

repo_score<- read_csv("repo_sim_scores_stats_co.csv")
label <- read_csv("oss_software_labelled.csv")


github_repos_157k <- read_csv("github_repos_157k.csv")

label <- read_csv("github_repos_157k_label.csv")

```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
ids = colnames(repo_score)
```



# Mean
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
mean_id = c()
for (i in (1:length(ids))){
  id = ids[i]
  if (grepl("mean", id)){
    mean_id <- append(mean_id, id) 
  }
}
repo_score_mean <- repo_score%>%
  select(slug, mean_id)%>%
  gather(software_type, mean,-slug)
```

# Max
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
max_id = c()
for (i in (1:length(ids))){
  id = ids[i]
  if (grepl("max", id)){
    max_id <- append(max_id, id) 
  }
}
repo_score_max <- repo_score%>%
  select(slug, max_id)%>%
  gather(software_type, max,-slug)

```

# Medain
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
median_id = c()
for (i in (1:length(ids))){
  id = ids[i]
  if (grepl("median", id)){
    median_id <- append(median_id, id) 
  }
}

repo_score_median <- repo_score%>%
  select(slug, median_id,description)%>%
  gather(software_type, median,-c(slug, description))

repo_score_median_dedup = repo_score_median %>% 
  distinct(slug, software_type, .keep_all = T)


```

# Classification
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
repo_score_median_dedup_classify<- repo_score_median_dedup%>%
  group_by(software_type)%>%
  mutate(cutoff = mean(median)+2.5*sd(median))%>%
  mutate(is_type = ifelse(median > cutoff, T, F))%>%
  select(slug, software_type, is_type, description)
  
  

#finalize bert lablled dataset
repo_score_wide = repo_score_median_dedup_classify%>%
  spread(software_type, is_type)%>%
  select(-description)


colnames(repo_score_wide) <- c("slug", "topics_ai_bert", "app_blockchain_bert", "prog_clang_bert","app_database_bert", "topics_dataviz_bert", "prog_java_bert", "prog_javascript_bert", "prog_php_bert", "prog_python_bert")


```

# Join term matching label and bert label
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
#original data merge with bert labels
github_repos_157k_label =  left_join(github_repos_157k, repo_score_wide, by ="slug")


#convert from wide format to long format

bert_ids = c("topics_ai_bert", "app_blockchain_bert", "prog_clang_bert","app_database_bert", "topics_dataviz_bert", "prog_java_bert", "prog_javascript_bert", "prog_php_bert", "prog_python_bert")


github_repos_157k_label_long = github_repos_157k_label%>%
  gather(software_type, IS_TYPE, -c(slug,description, readme, language,topics,commits,forks,stars,watchers))%>% 
  distinct(slug, software_type, .keep_all = T)%>%
  mutate(software_type = ifelse(software_type %in% c("topics_ai_bert", "topics_ai_tm"), "topics_ai",
                         ifelse(software_type %in% c("app_blockchain_bert", "app_blockchain_tm"), "app_blockchain",
                         ifelse(software_type %in% c("prog_clang_bert", "prog_clang_tm"), "prog_clang",
                         ifelse(software_type %in% c("app_database_bert", "app_database_tm"), "app_database",
                         ifelse(software_type %in% c("topics_dataviz_bert", "topics_dataviz_tm"), "topics_dataviz",
                         ifelse(software_type %in% c("prog_java_bert","prog_java_tm"), "prog_java",
                         ifelse(software_type %in% c("prog_javascript_bert", "prog_javascript_tm"), "prog_javascript",
                         ifelse(software_type %in% c("prog_php_bert", "prog_php_tm"), "prog_php",
                         ifelse(software_type %in% c("prog_python_bert", "prog_python_tm"), "prog_python", NA))))))))))


github_repos_157k_label_final <- github_repos_157k_label_long%>%
  select(slug, software_type,IS)

#write.csv(github_repos_157k_label_long, "/project/class/bii_sdad_dspg/uva_2021/dspg21oss/github_repos_157k_label.csv", row.names = F)
```

# Summarize count by software type
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
summary_table <- github_repos_157k_label_long%>%
  filter(bert == TRUE)%>%
  group_by(software_type)%>%
  summarize(n=n())%>%
  arrange(-n)%>% 
  mutate(prc = round(n / 157538, 2))%>% 
  mutate(category_type = ifelse(test = str_detect(string = software_type, pattern = "^sys_"), yes = "system", no = ""),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "^prog_"), yes = "programming", no = category_type),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "^app_"), yes = "applications", no = category_type),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "^topics_"), yes = "applications", no = category_type),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "database"), yes = "system", no = category_type),
         category_type = ifelse(test = str_detect(
           string = software_type, pattern = "virtual"), yes = "system", no = category_type))

summary_table%>%
  datatable()

ggplot(data=summary_table, aes(x=reorder(software_type, n), y=n, fill=category_type)) +
  geom_bar(stat="identity") +
  coord_flip() +
  scale_fill_manual(values=c("#56B4E9", "#232D4B", "#E57200")) +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  ggtitle("OSS Software Types Detected") +
  labs(caption = "Based on 7.3M GitHub Repo Descriptions") +
  scale_y_continuous(breaks=c(0, 200000, 400000, 600000, 800000), 
                     labels=c("0", "200k", "400k", "600k", "800k"))
```

